server:
  port: 80
spring:
  application:
    name: matcher-api
---

spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prd


---

spring:
  profiles:
    active: test
