server:
  port: 80
spring:
  application:
    name: matcher-api
---

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6739
---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prd