spring:
  application:
    name: matcher-api
  datasource:
    url: jdbc:mysql://database-1.cdqbol9rmvzu.ap-northeast-2.rds.amazonaws.com:3306/matcher?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
matcher:
  jwtSecretKey:
