spring:
  application:
    name: campusnow-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: com.campusnow.api.core.configuration.Mysql8DialectCustom

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error